language: php

# @see https://pantheon.io/blog/highest-lowest-testing-multiple-symfony-versions
matrix:
  include:
    - php: 8.1
      # Resolves to Symfony 6.
      env: 'HIGHEST_LOWEST="update"'
    - php: 8.0
      # Resolves to Symfony 5.
      env: 'HIGHEST_LOWEST="update --prefer-lowest"'

cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "vendor"

before_install:
  - composer selfupdate

install:
  # Load composer dependencies.
  - composer validate --no-check-all --ansi
  - 'composer -n ${HIGHEST_LOWEST-install} --prefer-dist -o'

script:
  - composer test

after_success:
  - ./vendor/bin/coveralls -vvv
